version: '3'

services:
  db:
    image: mongo:4.0.10
    volumes:
      - mongo_data:/data/db
  api:
    build:
      context: ./src/node_api_test
      dockerfile: ../../Dockerfile
    depends_on:
      - db
    env_file: .env_api
    ports:
      - 8000:8000
volumes:
  mongo_data: